name: Publish to PyPI

on:
  push:
    branches-ignore:
      - "**"
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish-pypi:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    container: ghcr.io/release-engineers/build-image-poetry:latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish to PyPI
        shell: bash
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          ./app.sh build
          ./app.sh publish-pypi
